#!/bin/bash

git fetch --tags

latestTag=$(git describe --abbrev=0 --tags)

latestVersion=${latestTag/*./}

newFixVersion=$((latestVersion + 1))

versionPrefix=${latestTag%.*}

newVersion=$versionPrefix.$newFixVersion

echo $newVersion

git push --tags
